### ISSUE TITLE
Label DB connections so they can be monitored

### ISSUE THREAD

**Issue by kwiatek-kainos** [lukaszbudnik/migrator#228]
@lukaszbudnik One suggestion to make the application easier to use.

In order to make it easier to monitor how Migrator connects with a DB server would be good set application_name upon connecting to the server. This would allow a user to monitor on the DB's side when Migrator is working on.
That feature can come helpful when there is a problem with applying a migration.

#### Steps to reproduce
I'm testing Migrator against a PostgreSQL server.
1. Start a migration.
2. List open DB connections.
```sql
SELECT
  application_name,
  query
FROM pg_catalog.pg_stat_activity
WHERE state IS NOT NULL;
```
```
    application_name    |                                                                       query                                                                       
  ------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------
   PostgreSQL JDBC Driver | SET application_name = 'PostgreSQL JDBC Driver'
   PostgreSQL JDBC Driver | SET application_name = 'PostgreSQL JDBC Driver'
                          | select name, source_dir as sd, filename, type, db_schema, created, contents, checksum from migrator.migrator_migrations order by name, source_dir
                          | create schema if not exists migrator
```
3. The listing shows JDBC connections and lib/pq connections.

#### Actual results
There is no application_name set for Migrator therefore it is hard to list activity of Migrator only.
On the other hand JDBC connections are labelled and it is easier to track them.

#### Expected
For a connection with Migrator application_name is set.
```sql
SET application_name = 'Migrator'
```

#### References
Documentation: https://www.postgresql.org/docs/9.5/runtime-config-logging.html#GUC-APPLICATION-NAME
Proposed function to change: https://github.com/lukaszbudnik/migrator/blob/627215949ecec3aab1112b09a4440a89b39d23e0/db/db.go#L69-L70

**Comment by lukaszbudnik** [comment]
@kwiatek-kainos it looks like the pg/lib supports `application_name` as a part of the connection string and can be used like this:

```
dataSource: "user=postgres dbname=migrator_test host=192.168.99.100 port=55432 sslmode=disable application_name=migrator"
```

Documentation also mentions that the application_name can be read from `PGAPPNAME` env variable or even fallback_application_name param.

Can you verify if that's the case?

**Comment by kwiatek-kainos** [comment]
Yes, I'm well aware of those options but this ticket is about increasing usability of the application.

I believe without this change migrator passes on responsibility to from its own (its implementation) to the end user (his configuration) to make monitoring straightforward.
Consequently **usability** gets degraded.

As I have given in the example pgjdbc/pgjdbc for Java has a sane default where the end user does not have to configure the driver to achieve the very same result.
I reckon in this regard pgjdbc is easier to use.

**Comment by lukaszbudnik** [comment]
Closing. This can be achieved by configuration.
